language: python

python:
  - 2.7

install:
  - pip install coveralls

script:
  - python setup.py install
  - coverage run --include=*spotipy_twisted* tests/tests.py
#TODO  - for file in examples/*.py; do python $file; done

after_success:
  - coverage report
  - coveralls
  - pip install pep8 pyflakes
  - pep8 *.py tests/*.py
  - pyflakes *.py tests/*.py

